-- premake5.lua
workspace "Advent of Code 2023"
   architecture "x64"
   configurations { "Debug", "Release", "Dist" }
   startproject "Day01A"

   -- Workspace-wide build options for MSVC
   filter "system:windows"
      buildoptions { "/EHsc", "/Zc:preprocessor", "/Zc:__cplusplus" }

OutputDir = "%{cfg.system}-%{cfg.architecture}/%{cfg.buildcfg}"

group "Core"
	include "Core/Build-Core.lua"
group ""

include "Day01A/Build-App.lua"
include "Day01B/Build-App.lua"
include "Day02A/Build-App.lua"
include "Day02B/Build-App.lua"
include "Day03A/Build-App.lua"
include "Day03B/Build-App.lua"
include "Day04A/Build-App.lua"
include "Day04B/Build-App.lua"
include "Day05A/Build-App.lua"
include "Day05B/Build-App.lua"
include "Day06A/Build-App.lua"
include "Day06B/Build-App.lua"
include "Day07A/Build-App.lua"
include "Day07B/Build-App.lua"
include "Day08A/Build-App.lua"
include "Day08B/Build-App.lua"
include "Day09A/Build-App.lua"
include "Day09B/Build-App.lua"
include "Day10A/Build-App.lua"
include "Day10B/Build-App.lua"
include "Day11A/Build-App.lua"
include "Day11B/Build-App.lua"
include "Day12A/Build-App.lua"
include "Day12B/Build-App.lua"
include "Day13A/Build-App.lua"
include "Day13B/Build-App.lua"
include "Day14A/Build-App.lua"
include "Day14B/Build-App.lua"
include "Day15A/Build-App.lua"
include "Day15B/Build-App.lua"
include "Day16A/Build-App.lua"
include "Day16B/Build-App.lua"
include "Day17A/Build-App.lua"
include "Day17B/Build-App.lua"
include "Day18A/Build-App.lua"
include "Day18B/Build-App.lua"
include "Day19A/Build-App.lua"
include "Day19B/Build-App.lua"
include "Day20A/Build-App.lua"
include "Day20B/Build-App.lua"
include "Day21A/Build-App.lua"
include "Day21B/Build-App.lua"
include "Day22A/Build-App.lua"
include "Day22B/Build-App.lua"
include "Day23A/Build-App.lua"
include "Day23B/Build-App.lua"
include "Day24A/Build-App.lua"
include "Day24B/Build-App.lua"
include "Day25A/Build-App.lua"
include "Day25B/Build-App.lua"
